/**
 * Auto generated file using cli command
 * _> node cli.cjs
 * Then select 'packages' option
 * Manual changes will be overwritten
 */

import { App, Plugin } from 'vue';

import { OrionAlertPlugin } from './Alert';
import { OrionAsidePlugin } from './Aside';
import { OrionAvatarPlugin } from './Avatar';
import { OrionAvatarGroupPlugin } from './AvatarGroup';
import { OrionButtonPlugin } from './Button';
import { OrionCardPlugin } from './Card';
import { OrionCarouselPlugin } from './Carousel';
import { OrionCarouselItemPlugin } from './CarouselItem';
import { OrionChatPlugin } from './Chat';
import { OrionChatDiscussionListPlugin } from './ChatDiscussionList';
import { OrionChatMessagePlugin } from './ChatMessage';
import { OrionCheckboxPlugin } from './Checkbox';
import { OrionChipsPlugin } from './Chips';
import { OrionColorPickerPlugin } from './ColorPicker';
import { OrionCropperPlugin } from './Cropper';
import { OrionDailyCalendarPlugin } from './DailyCalendar';
import { OrionDateRangePlugin } from './DateRange';
import { OrionDateTablePlugin } from './DateTable';
import { OrionDateWeekPlugin } from './DateWeek';
import { OrionDatepickerPlugin } from './Datepicker';
import { OrionDraggablePlugin } from './Draggable';
import { OrionDroppablePlugin } from './Droppable';
import { OrionEditorPlugin } from './Editor';
import { OrionFieldPlugin } from './Field';
import { OrionFooterFixedPlugin } from './FooterFixed';
import { OrionHorizontalScrollPlugin } from './HorizontalScroll';
import { OrionIconPlugin } from './Icon';
import { OrionIconSectionPlugin } from './IconSection';
import { OrionInputPlugin } from './Input';
import { OrionInputRangePlugin } from './InputRange';
import { OrionLayoutPlugin } from './Layout';
import { OrionListPlugin } from './List';
import { OrionLoaderPlugin } from './Loader';
import { OrionModalPlugin } from './Modal';
import { OrionNavAsidePlugin } from './NavAside';
import { OrionNavMainPlugin } from './NavMain';
import { OrionNavMainItemPlugin } from './NavMainItem';
import { OrionNavTabsPlugin } from './NavTabs';
import { OrionNavTopPlugin } from './NavTop';
import { OrionNotifPlugin } from './Notif';
import { OrionOtpPlugin } from './Otp';
import { OrionOverlayPlugin } from './Overlay';
import { OrionPagePlugin } from './Page';
import { OrionPaginatePlugin } from './Paginate';
import { OrionPasswordPlugin } from './Password';
import { OrionPhonePlugin } from './Phone';
import { OrionPopConfirmPlugin } from './PopConfirm';
import { OrionProgressBarPlugin } from './ProgressBar';
import { OrionProgressCirclePlugin } from './ProgressCircle';
import { OrionRadioPlugin } from './Radio';
import { OrionRatePlugin } from './Rate';
import { OrionSectionPlugin } from './Section';
import { OrionSelectPlugin } from './Select';
import { OrionStickerPlugin } from './Sticker';
import { OrionSwipePlugin } from './Swipe';
import { OrionTabNavPlugin } from './TabNav';
import { OrionTabPanePlugin } from './TabPane';
import { OrionTabsPlugin } from './Tabs';
import { OrionTextareaPlugin } from './Textarea';
import { OrionTimelinePlugin } from './Timeline';
import { OrionTimelinePanePlugin } from './TimelinePane';
import { OrionTimelinePillPlugin } from './TimelinePill';
import { OrionTogglePlugin } from './Toggle';
import { OrionTourPlugin } from './Tour';
import { OrionTourStepPlugin } from './TourStep';
import { OrionUploadPlugin } from './Upload';


const OrionComponentsPlugin: Plugin = {
	install (app: App, prefix: string) {
		OrionAlertPlugin.install?.(app, prefix);
		OrionAsidePlugin.install?.(app, prefix);
		OrionAvatarPlugin.install?.(app, prefix);
		OrionAvatarGroupPlugin.install?.(app, prefix);
		OrionButtonPlugin.install?.(app, prefix);
		OrionCardPlugin.install?.(app, prefix);
		OrionCarouselPlugin.install?.(app, prefix);
		OrionCarouselItemPlugin.install?.(app, prefix);
		OrionChatPlugin.install?.(app, prefix);
		OrionChatDiscussionListPlugin.install?.(app, prefix);
		OrionChatMessagePlugin.install?.(app, prefix);
		OrionCheckboxPlugin.install?.(app, prefix);
		OrionChipsPlugin.install?.(app, prefix);
		OrionColorPickerPlugin.install?.(app, prefix);
		OrionCropperPlugin.install?.(app, prefix);
		OrionDailyCalendarPlugin.install?.(app, prefix);
		OrionDateRangePlugin.install?.(app, prefix);
		OrionDateTablePlugin.install?.(app, prefix);
		OrionDateWeekPlugin.install?.(app, prefix);
		OrionDatepickerPlugin.install?.(app, prefix);
		OrionDraggablePlugin.install?.(app, prefix);
		OrionDroppablePlugin.install?.(app, prefix);
		OrionEditorPlugin.install?.(app, prefix);
		OrionFieldPlugin.install?.(app, prefix);
		OrionFooterFixedPlugin.install?.(app, prefix);
		OrionHorizontalScrollPlugin.install?.(app, prefix);
		OrionIconPlugin.install?.(app, prefix);
		OrionIconSectionPlugin.install?.(app, prefix);
		OrionInputPlugin.install?.(app, prefix);
		OrionInputRangePlugin.install?.(app, prefix);
		OrionLayoutPlugin.install?.(app, prefix);
		OrionListPlugin.install?.(app, prefix);
		OrionLoaderPlugin.install?.(app, prefix);
		OrionModalPlugin.install?.(app, prefix);
		OrionNavAsidePlugin.install?.(app, prefix);
		OrionNavMainPlugin.install?.(app, prefix);
		OrionNavMainItemPlugin.install?.(app, prefix);
		OrionNavTabsPlugin.install?.(app, prefix);
		OrionNavTopPlugin.install?.(app, prefix);
		OrionNotifPlugin.install?.(app, prefix);
		OrionOtpPlugin.install?.(app, prefix);
		OrionOverlayPlugin.install?.(app, prefix);
		OrionPagePlugin.install?.(app, prefix);
		OrionPaginatePlugin.install?.(app, prefix);
		OrionPasswordPlugin.install?.(app, prefix);
		OrionPhonePlugin.install?.(app, prefix);
		OrionPopConfirmPlugin.install?.(app, prefix);
		OrionProgressBarPlugin.install?.(app, prefix);
		OrionProgressCirclePlugin.install?.(app, prefix);
		OrionRadioPlugin.install?.(app, prefix);
		OrionRatePlugin.install?.(app, prefix);
		OrionSectionPlugin.install?.(app, prefix);
		OrionSelectPlugin.install?.(app, prefix);
		OrionStickerPlugin.install?.(app, prefix);
		OrionSwipePlugin.install?.(app, prefix);
		OrionTabNavPlugin.install?.(app, prefix);
		OrionTabPanePlugin.install?.(app, prefix);
		OrionTabsPlugin.install?.(app, prefix);
		OrionTextareaPlugin.install?.(app, prefix);
		OrionTimelinePlugin.install?.(app, prefix);
		OrionTimelinePanePlugin.install?.(app, prefix);
		OrionTimelinePillPlugin.install?.(app, prefix);
		OrionTogglePlugin.install?.(app, prefix);
		OrionTourPlugin.install?.(app, prefix);
		OrionTourStepPlugin.install?.(app, prefix);
		OrionUploadPlugin.install?.(app, prefix);
	},
};


export default OrionComponentsPlugin;

export { OrionComponentsPlugin };

export * from './Alert';
export * from './Aside';
export * from './Avatar';
export * from './AvatarGroup';
export * from './Button';
export * from './Card';
export * from './Carousel';
export * from './CarouselItem';
export * from './Chat';
export * from './ChatDiscussionList';
export * from './ChatMessage';
export * from './Checkbox';
export * from './Chips';
export * from './ColorPicker';
export * from './Cropper';
export * from './DailyCalendar';
export * from './DateRange';
export * from './DateTable';
export * from './DateWeek';
export * from './Datepicker';
export * from './Draggable';
export * from './Droppable';
export * from './Editor';
export * from './Field';
export * from './FooterFixed';
export * from './HorizontalScroll';
export * from './Icon';
export * from './IconSection';
export * from './Input';
export * from './InputRange';
export * from './Layout';
export * from './List';
export * from './Loader';
export * from './Modal';
export * from './NavAside';
export * from './NavMain';
export * from './NavMainItem';
export * from './NavTabs';
export * from './NavTop';
export * from './Notif';
export * from './Otp';
export * from './Overlay';
export * from './Page';
export * from './Paginate';
export * from './Password';
export * from './Phone';
export * from './PopConfirm';
export * from './ProgressBar';
export * from './ProgressCircle';
export * from './Radio';
export * from './Rate';
export * from './Section';
export * from './Select';
export * from './Sticker';
export * from './Swipe';
export * from './TabNav';
export * from './TabPane';
export * from './Tabs';
export * from './Textarea';
export * from './Timeline';
export * from './TimelinePane';
export * from './TimelinePill';
export * from './Toggle';
export * from './Tour';
export * from './TourStep';
export * from './Upload';
