name: Build documentation for pull-request

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'packages/*/docs/**'
      - '**.yml'

jobs:
  build-lib-pullrequest:
    name: Build Lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build lib
        run: npm run build

      - name: Run post build script
        run: node scripts/ci-build-lib.cjs

      - name: Upload Lib artifact
        uses: actions/upload-artifact@v4
        with:
          name: orion-build
          path: dist

  build-doc-pullrequest:
    name: Build Doc
    runs-on: ubuntu-latest
    needs: build-lib-pullrequest
    steps:
      - name: Download Lib artifact
        uses: actions/download-artifact@v4
        with:
          name: orion-build

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build doc
        run: npm run docs:build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
